### ISSUE TITLE
How can i test?

### ISSUE THREAD

**Issue by hhfa1990** [Otamay/esphome_climate_mirage#1]
How can I test this component?

**Comment by didi3r** [comment]
You need to load the component as an [external component](https://esphome.io/components/external_components.html) in your ESPHome configuration. Here is a sample of the config I wrote to make it work:

```yaml

...

external_components:
  - source:
      type: git
      url: https://github.com/Otamay/esphome_climate_mirage
      ref: main

remote_transmitter:
  id: remote_tx
  # name: "IR Transmitter"
  pin: GPIXX
  carrier_duty_percent: 50%

remote_receiver:
  id: remote_rx
  # name: "IR Receiver"
  pin:
    number: GPIXX
    inverted: true
    mode:
      input: true
      pullup: true
  # high 55% tolerance is recommended for some remote control units
  tolerance: 55%
  filter: 10us
  idle: 25ms
  dump: all

climate:
  - platform: mirage
    name: "AC"
    transmitter_id: remote_tx
    receiver_id: remote_rx

...
```

The component works for a Mirage v32 Inverter (Cool + Heat) unit. However, there is an issue with the current source code from this repo that prevents the climate control from showing in HomeAssistant. I made some changes to fix it in this [PR](https://github.com/Otamay/esphome_climate_mirage/pull/2). So, until the author fixes this repo, you can clone the repo, make the changes in your local, and load the component locally in your ESPHome configuration.
